# format terraform files
format:
    terraform fmt -recursive

# lint files
lint:
    uvx prek run --all-files

# update autogenerated documentation
docs:
    terraform-docs markdown . --output-file README.md
