# format terraform files
format:
    terraform fmt -recursive

# lint files
lint:
    #!/usr/bin/env bash
    set -e

    terraform fmt -recursive --check
    terraform init
    terraform validate
    tflint -f compact --recursive

# update autogenerated documentation
docs:
    terraform-docs markdown . --output-file README.md
